import type { Metadata } from "next";
import "@/app/styles/index.scss";

export const metadata: Metadata = {
  title: "Cleex Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <main className="app">{children}</main>
      </body>
    </html>
  );
}
